# Generated by Django 5.2.14 on 2026-05-07 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='anonymous', max_length=64)),
                ('action_type', models.CharField(choices=[('SEND_SOS', 'Send SOS'), ('NOTIFY_CONTACTS', 'Notify Emergency Contacts'), ('SHARE_LOCATION', 'Share Live Location'), ('RECOMMEND_SAFE_PLACE', 'Recommend Safe Place'), ('START_RECORDING', 'Start Audio/Video Recording'), ('INCREASE_MONITORING', 'Increase Monitoring Frequency'), ('ALERT_AUTHORITIES', 'Alert Authorities')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='EXECUTED', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='Low', max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safeher_agent_action',
                'ordering': ['-created_at'],
            },
        ),
    ]
