# Generated by Django 5.2.14 on 2026-05-07 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='anonymous', max_length=64)),
                ('alert_type', models.CharField(choices=[('SOS', 'SOS'), ('AUTONOMOUS', 'Autonomous AI'), ('VOICE', 'Voice Trigger'), ('MANUAL', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('risk_score', models.IntegerField(default=0)),
                ('contacts_notified', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safeher_emergency_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='anonymous', max_length=64)),
                ('keyword', models.CharField(max_length=100)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=1.0)),
                ('action_taken', models.CharField(default='ALERT_TRIGGERED', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safeher_voice_trigger',
                'ordering': ['-timestamp'],
            },
        ),
    ]
