# Generated by Django 5.2.14 on 2026-05-07 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='anonymous', max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('area_type', models.CharField(choices=[('normal', 'Normal'), ('isolated', 'Isolated'), ('crowded', 'Crowded')], default='normal', max_length=20)),
                ('time_of_day', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=10)),
                ('speed_kmh', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safeher_location_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='anonymous', max_length=64)),
                ('risk_score', models.IntegerField()),
                ('safety_score', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('factors', models.JSONField(default=dict)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safeher_risk_analysis',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
